### ISSUE TITLE
Feature request: Testing Examples and HowTos

### ISSUE THREAD

**Issue by stefanhuber** [driftyco/ionic-conference-app#183] opened 2016-04-07 10:25 UTC
Ionic is great!

There is a big problem still. I don't know how to setup a testing environment for ionic2 apps:
 - How can I write executalbe unit tests?
 - Where to put the unit tests?
 - What about e2e testing?

I am aware that there are so many different approaches to testing, but still a "recommended approach by the ionic team" would be so necessary!

Even this demo app has absolutely no testing!!! For a naive developer this would suggest that ionic apps don't need testing... Which is a problematic conclusion.

**Comment by jgw96** [comment] 2016-07-29 18:04
Hello, thanks for opening an issue with us! I will be closing this app as a duplicate of https://github.com/driftyco/ionic/issues/5331.

**Closed by jgw96** 2016-07-29 18:04 UTC
Labels: enhancement
