### ISSUE TITLE
can't ionic serve

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-conference-app#257] opened 2016-09-29 14:57 UTC
I have an error
```
Running 'serve:before' npm script before serve
> ionic-conference-app@ watch /Users/sober/ionic/demo
> ionic-app-scripts watch
[22:54:52]  ionic-app-scripts 0.0.23
[22:54:52]  watch started ...
[22:54:52]  build dev started ...
[22:54:52]  clean started ...
[22:54:52]  clean finished in 10 ms
[22:54:52]  copy started ...
[22:54:52]  typescript compiler started ...
[22:54:52]  lint started ...
[22:54:52]  

[22:54:53]  copy finished in 46 ms
[22:54:55]  typescript compiler ready in 2.22 s
[22:54:55]  bundle dev started ...
Error reading template file, "my-component-tpl.html": Error: ENOENT: no such file or directory, open '/Users/sober/ionic/demo/node_modules/@ionic/storage/node_modules/@angular/core/src/animation/my-component-tpl.html'

[22:55:01]  bundle dev finished in 6.80 s
[22:55:01]  sass started ...
[22:55:02]  sass finished in 942 ms
[22:55:02]  build dev failed:  Build failed

[22:55:03]  watch ready in 10.04 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Comment by larssn** [comment] 2016-09-29 16:39
Is this with a fresh clone, or a old one? Ionic was just updated to RC0, and a lot of breaking changes have happened.

**Comment by yozman** [comment] 2016-09-30 04:21
with the master branch,
and run `npm i`
then `ionic serve`

**Comment by jgw96** [comment] 2016-10-03 20:32
Hello, thanks for using Ionic! Most likely this is caused by you running NPM 2. Would you mind updating to npm 3 by running `npm install -g npm`? Since i cannot reproduce this issue I will be closing this issue for now.

**Closed by jgw96** 2016-10-03 20:32 UTC

**Comment by KarimMesallam** [comment] 2016-11-19 01:38
I had this issue fixed by updating the logger port, the live reload port and the HTTP port by running the following command: 

`ionic serve --dev-logger-port 53704 --livereload-port 35730 --port 8200 `
