### ISSUE TITLE
ReferenceError:Unknown plugin "transform-decorators-legacy" specified in "base"

### ISSUE THREAD

**Issue by FxLsoft3** [driftyco/ionic-conference-app#180] opened 2016-04-05 06:14 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which branch are you on?** master or typescript

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment] 2016-04-05 20:26
Could you give us more information, please? Filling out the information in the issue template is to help us help you. :smile:

What command are you running to get this error?
What branch are you on?
Can you run `ionic info` inside of the project and paste it here?

**Comment by FxLsoft3** [comment] 2016-04-06 02:55
When I run ionic serve,I have two problems ,that is
![image](https://cloud.githubusercontent.com/assets/13415380/14304500/f0c7e156-fbe5-11e5-899f-010b0ec39035.png)

**Comment by brandyscarney** [comment] 2016-04-06 19:26
@FxLsoft3 Can you run this command for now to fix the Unknown plugin error:

```
npm install babel-plugin-transform-decorators-legacy
```

We'll look into the cause of this.

I still need more info to help you with the other error. Can you please respond to my previous questions?

**Comment by jbraun27** [comment] 2016-04-07 01:57
I just grabbed the latest ionic-conference-app and ran into the same missing dependency, and after you resolve that one, you'll run into another. 

- npm install babel-plugin-transform-decorators-legacy
- npm install babel-preset-es2015

After that, you should be able to "ionic serve" and be back in business.

ionic info:
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS:
Node Version: v4.3.2

npm -v
2.14.12

**Comment by brandyscarney** [comment] 2016-04-07 02:21
Thanks for the info @jbraun27! This is something we'll need to account for, but just to add, updating npm to 3.x _should_ install these for you when you run `npm install`. 

You can run `sudo npm install -g npm` to update npm.

**Comment by jbraun27** [comment] 2016-04-07 03:14
Aaahhh.. perfect. yes, keeping versions in synch for all projects is a real challenge. Thank you @brandyscarney 
I see that Max Lynch and Microsoft's Ryan Salva presented a version of this code at //build/ 2016:
https://channel9.msdn.com/Events/Build/2016/B835 
But, there are some enhancements, additions, and code to connect to Azure and login providers etc.  Do you know if that code is going to be made available here or elsewhere?

**Comment by jbraun27** [comment] 2016-04-07 16:10
Disregard my last question, I see that the link to the code presented at /build// 2016 is included now in the comments section.

**Comment by tlancina** [comment] 2016-04-08 22:53
Hey this should be fixed for npm2 users with https://github.com/driftyco/ionic-gulp-tasks/commit/8024997103827d66170b82443a7d1160540806ed

**Closed by tlancina** 2016-04-08 22:53 UTC
Labels: needs reply

**Comment by ry928330** [comment] 2017-07-11 08:00
@brandyscarney  you solve my problem, thank you very much~

**Comment by ry928330** [comment] 2017-07-12 01:52
@brandyscarney  you solve my problem, thank you very much~
