### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by meeximum** [driftyco/ionic-conference-app#91] opened 2015-12-12 12:33 UTC
Hi, 

when I try ionic serve I got that exception

✗ Caught exception:
Error: spawn gulp ENOENT
   at exports._errnoException (util.js:746:11)
   at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
   at child_process.js:1144:20
   at process._tickCallback (node.js:355:11)
   at Function.Module.runMain (module.js:503:11)
   at startup (node.js:129:16)
   at node.js:814:3

The app starts, but the icons aren't shown :-(

**Comment by meeximum** [comment] 2015-12-12 12:35
Here my environement

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.11
Ionic App Lib Version: 2.0.0-beta.5
OS: Windows 8.1
Node Version: v0.12.7

**Comment by meeximum** [comment] 2015-12-12 16:47
It seems that the ionicons.ttf file is missing in the build directory.
I'm not sure if this is because of the exception?

**Comment by brandyscarney** [comment] 2015-12-12 19:05
There are new steps to run the conference app, please make sure you have gulp installed:
https://github.com/driftyco/ionic-conference-app#getting-started

Then make sure to run `gulp sass` in order to build the css, or `gulp sass watch` to watch changes to the Sass files.

**Comment by meeximum** [comment] 2015-12-12 19:09
yep, gulp is installed and the tasks work!
But still the exception running ionic serve, seems to be the hook
in ionic.config.js that causes the exception

**Comment by LuisOliveiraAlves** [comment] 2015-12-12 20:09
I got a similar error yesterday right after they updated some stuff. It was working just fine before they changed everything from js to ts. I tried running the new version of the conference app but it failed (I think it was this very same error). I thought it could be because I was running it on the ionic@alpha CLI version so I tried changing it to ionic@beta, but the error persisted.

**Comment by tlancina** [comment] 2015-12-12 20:15
@LuisOliveiraAlves are you on windows as well?

**Comment by tlancina** [comment] 2015-12-12 21:12
Hey I've just updated `ionic.config.js` to use the locally installed gulp instead so you don't need it globally, but I unfortunately don't have a windows machine to test on at the moment, so let us know if there are still errors when running serve.

**Comment by LuisOliveiraAlves** [comment] 2015-12-13 17:26
Yes, I am on windows 10. Still can't run it though. I don't think gulp is the problem as we were able to run ionic serve before just fine. We have gulp installed. I'm getting all kinds of errors now. I don't know why, but the dependencies are not being installed correctly. 

This version is still running fine, so I'm working with it: https://github.com/driftyco/ionic-conference-app/tree/e3dd4c843d2c1d93ecd79acce0eb70fafc0453e4

**Comment by tlancina** [comment] 2015-12-13 17:34
Hey it would be awesome if you could post the errors you're getting or the steps to reproduce them, otherwise it's very hard for us to do anything about it

**Comment by tlancina** [comment] 2015-12-13 19:55
@LuisOliveiraAlves saw what you meant about the dependencies, should be fixed with https://github.com/driftyco/ionic-conference-app/commit/8072c473075b81fca62954198c58bac88cbffa24.

Still looking into getting gulp to work on windows.

**Closed** 2015-12-13 20:13 UTC
