### ISSUE TITLE
Module not found: Error: Cannot resolve module 'web-animations.min'

### ISSUE THREAD

**Issue by nprail** [driftyco/ionic-conference-app#57] opened 2015-11-13 14:42 UTC
I downloaded the app then unzipped it and ran ionic serve and it gives me this:
![cmd](https://cloud.githubusercontent.com/assets/10778661/11148419/a905ddf4-89ea-11e5-8aa0-937b399601a3.PNG)

**Comment by brandyscarney** [comment] 2015-11-13 14:45
Hey, this is a duplicate of #56. See my comment there: https://github.com/driftyco/ionic-conference-app/issues/56#issuecomment-156266708

**Closed by brandyscarney** 2015-11-13 14:45 UTC

**Comment by brandyscarney** [comment] 2015-11-13 23:06
The conference app has been updated to alpha.32, please follow the below steps to get it working:

1. Install the latest version of the Ionic CLI (currently alpha.22): `npm install -g ionic@alpha`
2. Remove & and re-download the conference app: `git clone https://github.com/driftyco/ionic-conference-app`
3. Switch into that directory and run: `npm i`

Then you should be able to run `ionic serve` and other ionic commands. Please open a new issue if you find a different problem.

**Comment by sirfak** [comment] 2015-11-14 07:05
repated the step but still getting this error
![image](https://cloud.githubusercontent.com/assets/9669405/11162538/3d60c21a-8afa-11e5-83ff-e81d75e45c68.png)

**Comment by nprail** [comment] 2015-11-14 14:31
It works for me now.
