### ISSUE TITLE
Icon and splashscreen - RC3

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic-conference-app#317] opened 2016-11-18 21:32 UTC
While building ionic-conference-app , it builds with default icons and splash screen not the one with resources folder. It creates res folder with custom icons while in platform/android/res -- > default cordova icons are there... 
I'm facing this in my own app to so does this demo app of yours.
Using cordova 6.x version and tried with their tutorials nothing works..

/platform/android/res

![screen](https://cloud.githubusercontent.com/assets/5066436/20447381/75b81b1c-ae04-11e6-88e9-e90420599964.png)

/resources/android/splash
![drawable-land-ldpi-screen](https://cloud.githubusercontent.com/assets/5066436/20447294/1a2e1210-ae04-11e6-9065-e1be343cd1f4.png)

**Comment by ZiFFeL1992** [comment] 2016-11-20 19:26
https://github.com/driftyco/ionic-cli/issues/1683

**Comment by jgw96** [comment] 2016-11-21 21:06
Hello all! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1683. Thanks!

**Closed by jgw96** 2016-11-21 21:06 UTC
