### ISSUE TITLE
Storage does not work in user-data.ts

### ISSUE THREAD

**Issue by nurlan** [driftyco/ionic-conference-app#303] opened 2016-11-06 06:50 UTC
#### Short description of the problem:
Login and Account pages use Storage class, which does not work in web browser at the moment.

#### What behavior are you expecting?
It must work without any error

**Steps to reproduce:**
1. ionic serve
2. go to the login page and try to login
3. go to the account page

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
Error: Uncaught (in promise): Error: No available storage method found.
    at s (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at IDBOpenDBRequest.invoke (polyfills.js:3)
ErrorHandler.handleError @ error_handler.js:53
next @ application_ref.js:272
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
NgZone.triggerError @ ng_zone.js:278
onHandleError @ ng_zone.js:257
t.handleError @ polyfills.js:3
e.runGuarded @ polyfills.js:3
r @ polyfills.js:3
i @ polyfills.js:3
invoke @ polyfills.js:3
polyfills.js:3 Unhandled Promise rejection: No available storage method found. ; Zone: angular ; Task: Promise.then ; Value: Error: No available storage method found.
    at driverPromiseLoop (localforage.js:2218)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (ng_zone.js:236)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3) Error: No available storage method found.
    at driverPromiseLoop (http://localhost:8100/build/main.js:108848:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13422)
    at Object.onInvoke (http://localhost:8100/build/main.js:32536:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13373)
    at e.run (http://localhost:8100/build/polyfills.js:3:10809)
    at http://localhost:8100/build/polyfills.js:3:8911
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14051)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:32527:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:13987)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:11411)
o @ polyfills.js:3
r @ polyfills.js:3
i @ polyfills.js:3
invoke @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): Error: No available storage method found.
    at s (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at IDBOpenDBRequest.invoke (polyfills.js:3)
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by jgw96** [comment] 2016-11-07 17:14
Hello, thanks for using Ionic! Unfortunately I am not able to reproduce this error following your repro steps. What browser are you seeing this issue in? Also, are you using the latest master branch of the  conf app?

**Comment by jgw96** [comment] 2016-11-21 21:20
Hello all! As it seems it has been a while since there was any activity on this issue and I cannot reproduce it i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-11-21 21:20 UTC
Labels: needs reply

**Comment by TonyLuo** [comment] 2017-07-23 02:51
have the same error. after run ionic serve, then test it on chrome in mac os, everything is fine. when try to test it on android chrome, error occur:

**Error**

> Uncaught (in promise): Error: No available storage method found. Error: No available storage method found. at driverPromiseLoop (http://192.168.3.5:8100/build/vendor.js:116893:33) at t.invoke (http://192.168.3.5:8100/build/polyfills.js:3:9283) at Object.onInvoke (http://192.168.3.5:8100/build/vendor.js:4508:37) at t.invoke (http://192.168.3.5:8100/build/polyfills.js:3:9223) at r.run (http://192.168.3.5:8100/build/polyfills.js:3:4452) at http://192.168.3.5:8100/build/polyfills.js:3:14076 at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9967) at Object.onInvokeTask (http://192.168.3.5:8100/build/vendor.js:4499:37) at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9888) at r.runTask (http://192.168.3.5:8100/build/polyfills.js:3:5143)


**Stack**
```
Error: Uncaught (in promise): Error: No available storage method found.
Error: No available storage method found.
    at driverPromiseLoop (http://192.168.3.5:8100/build/vendor.js:116893:33)
    at t.invoke (http://192.168.3.5:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://192.168.3.5:8100/build/vendor.js:4508:37)
    at t.invoke (http://192.168.3.5:8100/build/polyfills.js:3:9223)
    at r.run (http://192.168.3.5:8100/build/polyfills.js:3:4452)
    at http://192.168.3.5:8100/build/polyfills.js:3:14076
    at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://192.168.3.5:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9888)
    at r.runTask (http://192.168.3.5:8100/build/polyfills.js:3:5143)
    at c (http://192.168.3.5:8100/build/polyfills.js:3:13535)
    at c (http://192.168.3.5:8100/build/polyfills.js:3:13221)
    at http://192.168.3.5:8100/build/polyfills.js:3:14067
    at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://192.168.3.5:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://192.168.3.5:8100/build/polyfills.js:3:9888)
    at r.runTask (http://192.168.3.5:8100/build/polyfills.js:3:5143)
    at o (http://192.168.3.5:8100/build/polyfills.js:3:2203)
    at IDBOpenDBRequest.invoke (http://192.168.3.5:8100/build/polyfills.js:3:10985)


```

Ionic Framework: 3.5.3
Ionic App Scripts: 2.0.2
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.1
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by TonyLuo** [comment] 2017-07-23 02:58
the odd thing is , i am testing it on mac os chrome, everything is fine ; then test it on android chrome, the error message will show on android chrome and mac chrome at the same time
