### ISSUE TITLE
"ionic serve" command not copying over "src/assets/fonts" to "www/assets/fonts" on build.

### ISSUE THREAD

**Issue by xgibbousx** [driftyco/ionic-conference-app#270] opened 2016-10-02 20:43 UTC
#### Short description of the problem:

"ionic serve" command not copying over "src/assets/fonts" to "www/assets/fonts" on build.

#### What behavior are you expecting?

For the fonts to copy over.

**Steps to reproduce:**
1. Run "ionic serve".
2. Get missing font errors in console.
3. Check the www/assets/fonts directory and see that there are not fonts in there.

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.6.0

**Comment by BradyLiles** [comment] 2016-10-03 15:14
I'm getting the same issue ^^^^

**Comment by jgw96** [comment] 2016-10-03 20:37
Hello, thanks for opening an issue with us. I am going to be closing this issue as a dupe of https://github.com/driftyco/ionic-app-scripts/issues/78.

**Closed by jgw96** 2016-10-03 20:37 UTC
