### ISSUE TITLE
Menu and Back Button Are Not Clickable

### ISSUE THREAD

**Issue by thomastthai** [driftyco/ionic-conference-app#318] opened 2016-11-20 01:18 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
With RC.3, the menu button to activate the side menu and also the back button aren't clickable. Clicking directly on the button doesn't do anything but clicking about 20 - 30 pixels to the right of the button activates it. That "hot" area on the right is about 5 to 10 pixels wide. The same code worked in RC.2.

#### What behavior are you expecting?

**Steps to reproduce:**
1. git clone the current ionic-conference-app
2. ionic install 
3. ionic serve, click those buttons

```
insert any relevant code between the above and below backticks (```)
N/A
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
> $ ionic info
> 
> Your system information:
> 
>  ordova CLI: 6.4.0
> Ionic Framework Version: 2.0.0-rc.3
> Ionic CLI Version: 2.1.12
> Ionic App Lib Version: 2.1.7
> Ionic App Scripts Version: 0.0.44
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Windows 10
> Node Version: v6.9.1
> Xcode version: Not installed
>

**Comment by brandyscarney** [comment] 2016-11-21 20:50
Hey @thomastthai, thanks for the issue! What environment are you using in order for this to happen? I am not seeing the issue in Chrome. :)

**Comment by jgw96** [comment] 2016-11-28 20:15
Hello @thomastthai are you still running into this issue?

**Comment by thomastthai** [comment] 2016-11-28 22:47
I will double check again.

**Comment by brandyscarney** [comment] 2017-01-04 19:21
I'm going to close this issue since we were unable to reproduce it and there have been no further updates. Please let us know if it is still an issue, including steps on how we can reproduce it, and I will reopen it. Thanks! 😄

**Closed by brandyscarney** 2017-01-04 19:21 UTC
Labels: needs reply

**Comment by thomastthai** [comment] 2017-01-04 19:22
I couldn't replicate it after making orher changes and removing packages.
Thanks.
