### ISSUE TITLE
When SearchBar focus (no text entered yet), not all items appear

### ISSUE THREAD

**Issue by ameralhomsi** [driftyco/ionic-conference-app#244] opened 2016-09-16 14:00 UTC
I face this problem in normal ionic tabs template also, when I put searchbar and focus it without typing any text, and try to scroll down, not all items appear, if i try to scroll down again (remove finger and swipe down again), the remaining items appear with tabs and header move up out of viewport.

i use iOS 9.3.5
Ionic 2.0.0-beta.11

Thanks

**Comment by jgw96** [comment] 2016-09-16 16:38
Hello, thanks for opening an issue with us. Unfortunately I cannot seem to reproduce this issue with either an iOS 9 emulator or an iPhone 5 running iOS 10. Are you still seeing this issue?

**Comment by ameralhomsi** [comment] 2016-09-16 18:13
1. The following picture when i scroll down most, as shown in this picture the last two items do not shown

![img_8359](https://cloud.githubusercontent.com/assets/18363520/18596365/733eacbe-7c51-11e6-87ca-51f7ba1363bd.PNG)


2. The next picture when i tried to scroll down again , as you can see the items go behind status bar


![img_8360](https://cloud.githubusercontent.com/assets/18363520/18596364/733c8bd2-7c51-11e6-82e1-f16ca3054905.PNG)


Note that this happens when keyboard appears

Thanks for helping

**Comment by ameralhomsi** [comment] 2016-09-19 17:36
Is there is answer for this ?, on my phone has problems ?

**Comment by ameralhomsi** [comment] 2016-10-22 14:58
does this question be replied on ?

**Comment by jgw96** [comment] 2016-11-21 21:27
Hello @ameralhomsi are you still having this issue with the latest version of the conference app?

**Comment by brandyscarney** [comment] 2017-01-04 20:25
I am going to close this since it's been awhile since there were any updates made and we weren't able to reproduce it. If you are able to reproduce this problem using the latest code from the conference app (running `2.0.0-rc.4`) let us know and we will reopen to look into it. Thanks!

**Closed by brandyscarney** 2017-01-04 20:25 UTC
Labels: needs reply
