### ISSUE TITLE
opening sidemenu on android makes app non-clickable

### ISSUE THREAD

**Issue by gauravsaini03** [driftyco/ionic-conference-app#118] opened 2015-12-29 19:42 UTC
Hello Team,

It's been really nice trying Ionic 2 and thanks for all your efforts.

Actually, I was testing this app and also sidemenu-starter template on android device and on my browser. It seems like when we toggle the menu after that we are unable to click on the entire screen. Although, it works fine in case of iOS.

Same thing happens when I run emulation on browser with iOS devices everything works good but as soon as I switch to any android device the similar problem occurs. 

Also, looks like this happened recently as month back I tried ionic-conference application menu was working fine but there were some glitches at that time also. 

Hoping to get it resolved soon :)

Thanks
Gaurav

**Comment by brandyscarney** [comment] 2015-12-29 19:48
This was fixed yesterday by this issue: https://github.com/driftyco/ionic2/issues/803

It will be in the next release of the Ionic SDK (2.0.0-alpha.46) at which point we will update the conference app & starters to use this version.

Please review our [contributing guidelines](https://github.com/driftyco/ionic-conference-app/blob/master/CONTRIBUTING.md) before submitting an issue. This issue is not specific to the conference app since it affects the sidemenu starter as well, so please report issues similar to this in the [ionic2 repository](https://github.com/driftyco/ionic2/issues) (if the issue isn't already reported). Thanks so much! :smile:

**Closed by brandyscarney** 2015-12-29 19:48 UTC
