### ISSUE TITLE
The code set enablemenu does not work correct when app init

### ISSUE THREAD

**Issue by lhwsa2010** [driftyco/ionic-conference-app#200] opened 2016-06-03 03:28 UTC
**Note: for support questions, please use one of these channels:**

#### Short description of the problem:
Code:  
this.userData.hasLoggedIn().then((hasLoggedIn) => {
hasloggedIn='true';// set hasloggedIn value
this.enableMenu(hasLoggedIn === 'true');
});

 set set hasloggedIn is 'true' or 'false',the menu does not work correct,

#### What behavior are you expecting?

when i set hasloggedIn='true',the menu should show Account and Logout.
when i set hasloggedIn='false',the menu should show Login and Singup.

Did i make mistake??

**Comment by brandyscarney** [comment] 2016-06-03 19:44
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

**Comment by wberger** [comment] 2016-08-09 09:12
This is still an issue within the app. Has this been posted (and answered) somewhere in the forum? 
Why does
```
this.menu.enable(loggedIn, 'loggedInMenu');
this.menu.enable(!loggedIn, 'loggedOutMenu');
```
not work for loggedIn === true, when the app is starting? 

Moving the call to `platform.ready()` or `ngAfterViewInit()`didn't help as well.

**Comment by wberger** [comment] 2016-08-09 09:50
@brandyscarney After further code inspection, I would say this is an issue with the conference app.

In [tutorial.ts](https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/tutorial/tutorial.ts) the implementations of `ionViewDidEnter` and `ionViewWillLeave` disable and enable the menu respectively. This interferes with the login-based calls in app.ts. ionViewWillLeave should also perform a login-based menu activation.

**Comment by brandyscarney** [comment] 2016-08-09 14:57
@wberger Sorry but I don't understand what the issue is. Could you explain the steps I could take to reproduce this, as well as what you expect?

**Comment by lhwsa2010** [comment] 2016-08-10 03:27
@wberger @brandyscarney  I have solved it. It is due to the app itself and the developer was certainly in thinking what to eat for lunch. ^_^
Because when view enter in tutorial the menu have been set disabled.No matter true or false you set,it never trigger the event change,so you never get the result what you want.Just delete the menu enable set code it will do fine.
ps: I think the app's logic should change to：
when the app enter in  ,it show the splash image,and when the default data has load all done,it decide which view will show. Just in my mind.

**Closed** 2016-08-10 03:30 UTC
