### ISSUE TITLE
Android Roboto font no longer included in rc0

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-conference-app#273] opened 2016-10-03 20:21 UTC
#### Short description of the problem:
When getting a completely fresh clone of this repo, and running ionic serve`, the "Roboto" font is no longer included or automatically applied in rc0

#### What behavior are you expecting?
As per Beta 11 and before, I would expect the Roboto font to be applied for `md` mode.

**Steps to reproduce:**
1.  Get a fresh clone of the ionic-conference-app
2.  Run npm install
3.  Run ionic serve (make sure you're testing with `md` mode)
4.  Notice that the Roboto font files are not included anywhere, and that the fallback font is used instead.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by jgw96** [comment] 2016-10-03 20:41
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/73. Thanks!

**Closed by jgw96** 2016-10-03 20:41 UTC
