### ISSUE TITLE
Balnk page after splash hide Android !

### ISSUE THREAD

**Issue by jehadja** [driftyco/ionic-conference-app#345] opened 2017-01-17 02:43 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

trying to run fresh download form conference-app on Android 7.1.1 API level 25, 
The SPLASH show up when application load Splash hide bank page appear and stacked there 
while its work good with ios and web -- serve 
 
``ionic emulate  android --livereload --consolelogs --serverlogs
``

```
[05:28:39]  console.log: Angular 2 is running in the development mode. Call enableProdMode() to enable the production 
            mode. 
[05:28:40]  console.warn: Native: deviceready did not fire within 2000ms. This can happen when plugins are in an 
            inconsistent state. Try removing plugins from plugins/ and reinstalling them. 
[05:28:40]  error opening ws message: {"category":"console","type":"log","data":["DEVICE READY FIRED AFTER",2934,"ms"]} 
[05:28:40]  error opening ws message: {"category":"console","type":"info","data":["Ionic Storage 
            driver:","asyncStorage"]} 
[05:28:45]  console.warn: Google Maps API warning: NoApiKeys 
            https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys 
```

**Expected behavior:**

work normally 

**Steps to reproduce:**

```
git clone https://github.com/driftyco/ionic-conference-app.git
cd ionic-conference-app
npm install
cordova platform add  android ios
ionic emulate  android -l -c -s
or
ionic run  android --livereload --consolelogs --serverlogs 
```

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5-201701112208
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by liangwenzhong** [comment] 2017-01-20 06:38
i got the same issues~~~

**Comment by jgw96** [comment] 2017-01-26 20:56
Hello all! Unfortunately I cannot reproduce this issue on either a 7.1.1 simulator or a Nexus 6 running Android 7.1.1, are you guys still having this issue?

**Comment by jb-int** [comment] 2017-02-06 15:50
I'm seeing the same issue

**Comment by jgw96** [comment] 2017-02-08 22:32
Hello all! As it seems it has been a while since there was any activity on this issue and we cannot reproduce it i will be closing it for now.  Feel free to comment if you are still running into this issue. Thanks for using Ionic! @jb-int , would you mind opening a seperate issue [here](https://github.com/driftyco/ionic)? This repo is for issues specifically related to the ionic conf app.

**Closed by jgw96** 2017-02-08 22:32 UTC
Labels: needs reply

**Comment by ProximaHaiz** [comment] 2017-04-18 15:34
When build app from https://github.com/driftyco/ionic-conference-app,
for android and install it on my android device (6.0.1) all works fine. But when i try to launch it on Genymotion emulator(ionic run adnroid or via android-x86-debug.apk file), i have white screen after splash hide.

![howitslookongenymotipn](https://cloud.githubusercontent.com/assets/14352123/25139310/8ccf6cba-2465-11e7-9d90-9c327c237ceb.png)


I can click the buttons and open the menu, but components are not displayed.
Genymotion device is Samsung Galaxy S6, android version 6.0.0, API23.
Screen from chrome device inspect:

![consolelook](https://cloud.githubusercontent.com/assets/14352123/25139321/936a3442-2465-11e7-882d-a242ffa4cea2.png)


consoleLook.png1563x1045 38.1 KB
My ionic info:
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.2.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.2
Xcode version: Not installed

Does anyone know what might be the problem?
