### ISSUE TITLE
Show Schedules for 2 days

### ISSUE THREAD

**Issue by SGEDA** [driftyco/ionic-conference-app#378] opened 2017-04-05 18:02 UTC
i would show my schedules for 2 days
thank you

**Comment by brandyscarney** [comment] 2017-04-05 18:13
Duplicate of https://github.com/driftyco/ionic-conference-app/issues/189, thanks!

**Closed by brandyscarney** 2017-04-05 18:13 UTC

**Comment by SGEDA** [comment] 2017-04-05 18:36
Okey thank you i'm going to read it

**Comment by SGEDA** [comment] 2017-04-07 20:22
plaese can you help i did not find the solution.
  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=aminesged@gmail.com&idSignature=22>
