### ISSUE TITLE
/build directory contains no html files

### ISSUE THREAD

**Issue by meeximum** [driftyco/ionic-conference-app#114] opened 2015-12-25 11:34 UTC
Hi,

somehow the ionic.config.js is ignored, as there are no html files copied to the www/build directory?

I just cloned the latest ionic-conference-app did a npm install and at ionic serve, I got following error in the console:
**Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:8100/build/app.html**

My system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.14
Ionic App Lib Version: 2.0.0-beta.7
OS: Windows 8.1
Node Version: v0.12.7

**Comment by brandyscarney** [comment] 2015-12-28 16:09
Could you try updating to the latest CLI beta version and see if that fixes it?

```
Ionic CLI Version: 2.0.0-beta.15
```

**Comment by meeximum** [comment] 2015-12-28 16:17
perfect! It's working :-)

2015-12-28 17:09 GMT+01:00 Brandy Carney <notifications@github.com>:

> Could you try updating to the latest CLI beta version and see if that
> fixes it?
>
> Ionic CLI Version: 2.0.0-beta.15
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-conference-app/issues/114#issuecomment-167595862>
> .
>



-- 
Markus Reich
Moosbach 28/2
6392 St. Jakob i.H.
www.markusreich.at
markus.reich@markusreich.at

**Comment by brandyscarney** [comment] 2015-12-28 16:34
Awesome! :smile: Closing this.

**Closed by brandyscarney** 2015-12-28 16:34 UTC

**Comment by koo9** [comment] 2016-04-23 22:28
having the same issue. update everything to the latest.
Your system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.1.1

nothing output to the www/build folder.

any idea?

**Comment by brandyscarney** [comment] 2016-04-24 16:25
Can you try running `npm install` again? The conference app is using beta 6. Did you clone it recently or has it been awhile? Also, which branch are you using?

**Comment by koo9** [comment] 2016-04-24 16:52
hi Brandy,

Thanks for replying on Sunday :)

I have tried `npm install` but no help. I just downloaded the zip file from the main branch. 
guess it's outdated project structure as the ionic.config.js is obsoleted. it seems like the gulp task is not picking up.

**Comment by brandyscarney** [comment] 2016-04-25 15:58
@koo9 Unfortunately I'm not able to reproduce this. I cloned the conference app from master and ran `npm install`, I get the following running `ionic info`:

```
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Node Version: v4.4.2
```

I'm confused that yours is printing `Ionic Framework Version: 2.0.0-beta.3` since it should be installing `2.0.0-beta.6` as of 4 days ago. Can you try removing the `node_modules` folder and doing a fresh `npm install`?

**Comment by koo9** [comment] 2016-04-25 16:00
Well do.  Thx!


Sent from my Samsung device

-------- Original message --------

**Comment by koo9** [comment] 2016-04-26 15:25
hi Brandy, 

downloaded the code again and did a clean install. works fine now. 

a question though, when starting up an app like google business, the splash screen shows up instantly and the UI shows up very quickly after. the app seems to load for a few second (4-5 seconds of white screen) before the UI shows up, now is it expected?
