### ISSUE TITLE
Scrollbar appearing on menu toggle

### ISSUE THREAD

**Issue by MarkXBD** [driftyco/ionic-conference-app#198] opened 2016-05-24 06:04 UTC
#### Short description of the problem:

When toggling the menu button, a scrollbar appears on the active `<ion-content>` element. (Even when there is not enough content to scroll)

**Steps to reproduce:**
1. Start up the conference app.
2. Go to the Map tab. Note there is no scrollbar visible.
3. Click the hamburger menu icon to open the menu.
4. Close the menu.
5. Note how there is now a scrollbar on the right side of the screen.

Same can be done for the 'About' page, in which case the scroll bar will appear in the top left corner (small block just below the hamburger menu). The strange thing is that if the page is redrawn, the scrollbar disappears.

Branch: Typescript

Tested on:
Chrome 50.0.2661.102
Android 6.0.1
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 8.1
Node Version: v0.12.4

![map_scrollbar](https://cloud.githubusercontent.com/assets/12723919/15493715/c9d45a10-21c0-11e6-92dd-4dbf743e3067.png)

**Comment by brandyscarney** [comment] 2016-05-25 21:53
Are you seeing this in the browser or only on a device/emulator?

**Comment by MarkXBD** [comment] 2016-05-25 22:49
Both on the Chrome browser and on my device (oneplus one, android 6.0.1)

**Comment by brandyscarney** [comment] 2016-07-08 01:09
Unfortunately I haven't been able to reproduce this. Are you still able to with the latest version?

**Comment by MarkXBD** [comment] 2016-07-08 01:34
I just tested and still have the same issue with the latest version of the conference app and Chrome (51.0.2704)

**Comment by jgw96** [comment] 2016-09-16 16:36
@MarkXBD I just tested this with a Moto X running Android 5.1.1, a Nexus 7 running Android 6.0.1 and a Nexus 6 running Android 7.0 and I cannot seem to reproduce this issue. I also cannot repro this issue in Chrome 53 (the latest stable). Are you still seeing this issue?

**Comment by jgw96** [comment] 2016-11-21 21:31
Hello all! As it seems it has been a while since there was any activity on this issue and I cannot repro it i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2016-11-21 21:31 UTC
Labels: bug, needs reply
