### ISSUE TITLE
Ionic serve with Windows 10

### ISSUE THREAD

**Issue by Vultur** [driftyco/ionic-conference-app#83] opened 2015-11-26 06:32 UTC
./~/moment/moment.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./D:/Program Files (x86)/nodejs/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/buildin/module.js in F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment
resolve file
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts doesn't exist
resolve directory
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist (directory default file)
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js\package.json doesn't exist (directory description file)
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\moment\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts]
 @ ./~/moment/moment.js 1:0-127,./www/app/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./D:/Program Files (x86)/nodejs/node_modules/ionic/node_modules/ionic-app-lib/node_modules/css-loader/index.js in F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app
resolve file
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js doesn't exist
resolve directory
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js doesn't exist (directory default file)
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js\package.json doesn't exist (directory description file)
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.webpack-loader.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.web-loader.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.loader.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\css-loader\index.js.js]
 @ ./www/app/app.scss 4:14-509,./www/app/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./D:/Program Files (x86)/nodejs/node_modules/ionic/node_modules/ionic-app-lib/node_modules/style-loader/addStyles.js in F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app
resolve file
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts doesn't exist
resolve directory
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js doesn't exist (directory default file)
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js\package.json doesn't exist (directory description file)
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\www\app\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\style-loader\addStyles.js.ts]
 @ ./www/app/app.scss 7:13-141,./~/@reactivex/rxjs/dist/cjs/util/root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./D:/Program Files (x86)/nodejs/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/buildin/module.js in F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util
resolve file
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts doesn't exist
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js doesn't exist
resolve directory
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js doesn't exist (directory default file)
  F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js\package.json doesn't exist (directory description file)
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.ts]
[F:\Workspaces\com.inleadcn.duang\02.duangClient\01.Project\v2.0r\com.inleadcn.duang\com.inleadcn.duang\node_modules\@reactivex\rxjs\dist\cjs\util\D:\Program Files (x86)\nodejs\node_modules\ionic\node_modules\ionic-app-lib\node_modules\webpack\buildin\module.js.js]
 @ ./~/@reactivex/rxjs/dist/cjs/util/root.js 1:0-127 (CLI v2.0.0-alpha.25)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.37
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
OS:
Node Version: v5.0.0

**Comment by tlancina** [comment] 2016-02-02 16:42
Looks to be a duplicate of https://github.com/driftyco/ionic/issues/5064, feel free to reopen if this is not the case, thanks!

**Closed by tlancina** 2016-02-02 16:42 UTC
