### ISSUE TITLE
Can't resolve all parameters for provideLocationStrategy

### ISSUE THREAD

**Issue by dragonahao** [driftyco/ionic-conference-app#275] opened 2016-10-04 00:43 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
metadata_resolver.js:499Uncaught Error: Can't resolve all parameters for provideLocationStrategy: (PlatformLocation, ?, Config).
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by dragonahao** [comment] 2016-10-04 00:44
i use ionic-conference demos and it occurred , what should i do to resolve it?

**Comment by dragonahao** [comment] 2016-10-05 00:23
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0-201610041708
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v6.7.0

**Comment by jgw96** [comment] 2016-10-21 19:17
Hello, thanks for using Ionic! Unfortunately I cannot reproduce this issue, can you try cloning the app and trying again?

**Comment by brandyscarney** [comment] 2016-11-21 21:00
I'm going to close this since there have been several changes since this was reported and we are not able to reproduce it. If it's still an issue try updating to the latest version of the CLI: `npm install -g ionic`, cloning the conference app, and then reinstalling node modules: `npm install`. If it's _still_ an issue after that let us know and we will reopen. Thanks! :)

**Closed by brandyscarney** 2016-11-21 21:00 UTC
Labels: needs reply
