### ISSUE TITLE
Beta-11: Menu white background overlay and not show menu list

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-conference-app#226] opened 2016-08-09 16:56 UTC
_From @nhohb07 on August 9, 2016 16:53_

![image](https://cloud.githubusercontent.com/assets/5916323/17525188/d82e3402-5e8b-11e6-8e73-e41f62f118dc.png)

Hi everyone! I try to build on ios app conference, the white menu error and no one menu item displayed. And my application is built from beta-9 was similar error, please review this issue to help me in the most recent version can build, I need this issue resolved urgently, thanks !

_Copied from original issue: driftyco/ionic#7626_

**Comment by brandyscarney** [comment] 2016-08-09 17:16
I'm not able to reproduce this using the latest version of the conference app. Are there any steps I need to take to reproduce this? See http://g.recordit.co/yz8s9FZ4He.gif

**Comment by alexbainbridge** [comment] 2016-08-09 17:20
Hi Brandy
I have seen this in a non conference app (but has a side menu) - let me see if I work out how I did it (its something to do with moving quickly I think, as only happens a occassionally)

Reason I hadn't raised it (yet) is because I was keeping an eye on https://github.com/driftyco/ionic/issues/7564 and wondering if that was the same issue

**Comment by alexbainbridge** [comment] 2016-08-09 17:58
Hi Brandy

OK I got this to work (fail)

1) Mac / Google Chrome (Desktop)

Cordova CLI: 5.4.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.5 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

2) Latest version of the conference app

3) Add mode IOS to bootstrap

ionicBootstrap(ConferenceApp, [ConferenceData, UserData], {
  mode: 'ios'
});

4) Click on menu icon (on a subpage), then click on an item e.g speakers (non logged in menu), then click on menu icon...... repeat..... about 1 time in 10 fails (and get the blank sidemenu). Speed is not necessarily the issue..... its just about repeating....    its intermittent, no specific sequence causes the issue to occur (as far as I can see)

Wish we were talking about this in the ionic repo rather than conf app one :)

**Comment by alexbainbridge** [comment] 2016-08-09 17:58
I should add, I couldnt get the conference app to fail when I didn't add ios as the mode.....

**Comment by brandyscarney** [comment] 2016-08-09 18:20
hey @alexbainbridge, thanks for the steps! I've tried following them but I'm still not able to reproduce it. I added `ios` mode to the bootstrap and tried reproducing it in both chrome and a simulator. I'm not sure what you mean by "click on menu icon (on a subpage)" since the menu icon doesn't show up on the subpages. Are you adding it in? I tried clicking on the menu icon over and over and also clicking different menu items over and over. I wasn't able to get a white screen though.

**Comment by jgw96** [comment] 2016-08-09 18:28
I would like to add that i tested this issue with an iphone 5 running ios 10 and an Iphone 6s simulator running 9.3.2 and i am also not able to reproduce this issue.

**Comment by alexbainbridge** [comment] 2016-08-09 18:30
Hi Brandy

Hummm 

Re steps - I said menu item (e.g speakers) then when you are on speakers page, click menu (hamburger) icon   

And do that over and over, clicking one so the other shows.

If I can get it to happen (blank side menu), are there any events or anything I could be logging that would be helping you?

**Comment by alexbainbridge** [comment] 2016-08-09 18:36
Here is a gif of it happening

![](http://g.recordit.co/g8DHkcBBD7.gif)

**Comment by brandyscarney** [comment] 2016-08-09 18:39
Thanks for the gif! I was able to reproduce it in Safari, but not Chrome. :)

**Comment by alexbainbridge** [comment] 2016-08-09 18:40
Ha, I just tried Safari and got it to fail also.... that was going to be my next update!

**Comment by brandyscarney** [comment] 2016-08-09 18:44
The cause is the `ion-menu` not getting the class `show-menu` added to it, _why_ this isn't being added is still to be discovered. I'll move this to the ionic repo. Thanks for the help!

**Comment by alexbainbridge** [comment] 2016-08-09 18:53
New in 11, if that helps narrow it down a bit.... (and updated Angular of course)

**Comment by brandyscarney** [comment] 2016-08-09 18:54
Thanks! I'm going to close this issue in favor of this one: https://github.com/driftyco/ionic/issues/7629

**Closed by brandyscarney** 2016-08-09 18:54 UTC
Labels: menus, platform:ios
