### ISSUE TITLE
Android 4.4.2 and 4.4.4 Tabs blank, but working

### ISSUE THREAD

**Issue by fonziedave** [driftyco/ionic-conference-app#237] opened 2016-08-29 11:26 UTC
On Android 4.4.2 and 4.4.4 the bottom tabs are blank, but they are working. If one of the tabs is clicked, the label is visible and animated and vanishes afterwards.

Tested with two different devices (LG L70 and MiPad 1).

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v5.12.0

Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v5.12.0

Update: crosswalk solves this problem but increases app size significantly. Crosswalk Project Lite is smaller but deactivates geolocation.

**Comment by jgw96** [comment] 2016-09-16 16:30
Hello, thanks for opening an issue with us! This is actually caused by this bug https://github.com/driftyco/ionic/issues/7604 . Because of that I am going to mark this one as blocked. Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-09-19 03:43
Hello, I am happy to report that this issue has been fixed. When the conf app is updated to beta 12 I will close this issue. Thanks for using Ionic!

**Comment by jashif** [comment] 2016-09-22 15:24
Hi 

I recently created a ionic2 application.  In my application I have ion-menu and ion-tab. Am getting a issue when ever ion -menu is there  the tab wont show. if I remove menu from the app and run then the tab will show properly. this issue is happening only in android version 4.4.2 .

**Comment by AbuHani** [comment] 2016-09-28 19:13
Hi,

i have the same issue, when beta 12 release date??

**Comment by jgw96** [comment] 2016-10-03 20:35
Hello all! The conference app has now been updated to RC.0 which fixed the blocking bug. Because of this I will be closing this issue for now. Thanks!

**Closed by jgw96** 2016-10-03 20:35 UTC
Labels: blocked
